title = 'kakudo.org'
baseURL = 'https://kakudo.org/'

enableGitInfo = true

googleAnalytics = 'G-N83S1TXH7H'

[params]
  images = ['thumbnail.png'] # Open Graph

[markup]
  [markup.highlight]
    style = 'onedark'
    tabWidth = 2
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # For raw HTML

[permalinks]
  blog = '/blog/:filename/'

[taxonomies]