baseURL = 'https://kakudo.org/'
languageCode = 'ja'
title = '覚道健太郎'

pluralizelisttitles = false

[markup]
  [markup.highlight]
    style = 'onedark'
    tabWidth = 2
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # For raw HTML

[permalinks]
  blog = '/blog/:filename/'
